name: Crystal CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DOCTL }}
    - name: Push
      uses: ripplr-io/docr-docker-publish@v1
      with:
        image_path: jgaskins/cloud_events_example
        dockerfile: examples/hello_world/Dockerfile
